/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as HubRouteImport } from './routes/hub'
import { Route as ExecuteRouteImport } from './routes/execute'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as AiWriterRouteImport } from './routes/ai-writer'
import { Route as IndexRouteImport } from './routes/index'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecuteRoute = ExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWriterRoute = AiWriterRouteImport.update({
  id: '/ai-writer',
  path: '/ai-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-writer': typeof AiWriterRoute
  '/brain': typeof BrainRoute
  '/execute': typeof ExecuteRoute
  '/hub': typeof HubRoute
  '/pipeline': typeof PipelineRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-writer': typeof AiWriterRoute
  '/brain': typeof BrainRoute
  '/execute': typeof ExecuteRoute
  '/hub': typeof HubRoute
  '/pipeline': typeof PipelineRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-writer': typeof AiWriterRoute
  '/brain': typeof BrainRoute
  '/execute': typeof ExecuteRoute
  '/hub': typeof HubRoute
  '/pipeline': typeof PipelineRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-writer'
    | '/brain'
    | '/execute'
    | '/hub'
    | '/pipeline'
    | '/plan'
    | '/review'
    | '/settings'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-writer'
    | '/brain'
    | '/execute'
    | '/hub'
    | '/pipeline'
    | '/plan'
    | '/review'
    | '/settings'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/ai-writer'
    | '/brain'
    | '/execute'
    | '/hub'
    | '/pipeline'
    | '/plan'
    | '/review'
    | '/settings'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWriterRoute: typeof AiWriterRoute
  BrainRoute: typeof BrainRoute
  ExecuteRoute: typeof ExecuteRoute
  HubRoute: typeof HubRoute
  PipelineRoute: typeof PipelineRoute
  PlanRoute: typeof PlanRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execute': {
      id: '/execute'
      path: '/execute'
      fullPath: '/execute'
      preLoaderRoute: typeof ExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-writer': {
      id: '/ai-writer'
      path: '/ai-writer'
      fullPath: '/ai-writer'
      preLoaderRoute: typeof AiWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWriterRoute: AiWriterRoute,
  BrainRoute: BrainRoute,
  ExecuteRoute: ExecuteRoute,
  HubRoute: HubRoute,
  PipelineRoute: PipelineRoute,
  PlanRoute: PlanRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
